apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: asiayo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3
  