apiVersion: batch/v1
kind: Job
metadata:
  name: wordpress-db-init
  namespace: asiayo
  labels:
    app: wordpress
    component: db-init
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: db-init
        image: mysql:8.0.31
        command: ['sh', '-c']
        args:
        - |
          # 等待 MySQL Router 就緒
          until mysql -h ${WORDPRESS_DB_HOST} -u root -p"${MYSQL_ROOT_PASSWORD}" -e "SELECT 1"; do
            echo "等待 MySQL 就緒..."
            sleep 5
          done

          # 檢查資料庫是否存在
          if mysql -h ${WORDPRESS_DB_HOST} -u root -p"${MYSQL_ROOT_PASSWORD}" -e "USE wordpress; SHOW TABLES;" 2>/dev/null; then
            echo "WordPress 資料庫已存在，跳過初始化"
            exit 0
          fi

          echo "MySQL 已就緒，開始初始化資料庫..."
          
          # 執行初始化
          mysql -h ${WORDPRESS_DB_HOST} -u root -p"${MYSQL_ROOT_PASSWORD}" -e "
          CREATE DATABASE IF NOT EXISTS wordpress
          CHARACTER SET utf8mb4
          COLLATE utf8mb4_unicode_ci;
          "
          
          if [ $? -eq 0 ]; then
            echo "資料庫初始化完成"
          else
            echo "資料庫初始化失敗"
            exit 1
          fi
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-cluster-secret
              key: rootPassword
        - name: WORDPRESS_DB_HOST
          value:  mysql
      restartPolicy: OnFailure
      